baseURL = 'https://nurbeksultanov.com/'
languageCode = 'en-us'
title = 'Nurbek Sultanov'
theme = 'PaperMod'

[params]
    [[homeInfoParams]]
        Title = 'Nurbek Sultanov'
        Content = 'Hello. I love playing videogames, and also creating them.'
    [[socialIcons]]
        name = 'linkedin'
        url = 'https://www.linkedin.com/in/nurbeksultanov/'
    [[socialIcons]]
        name = 'github'
        url = 'https://github.com/sultanovN'

    [[cover]]
        linkFullImages = true

[params.meta]
    favicon = false
    svg = true
    faviconVersion = "1"

[menus]
  [[menus.main]]
    name = 'HOME'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'RESUME'
    url = 'https://nurbeksultanov.com/pdf/Resume_Nurbek_Sultanov.pdf'
    target="_blank"
    weight = 20
  [[menus.main]]
    name = 'PROJECTS'
    url = 'https://nurbeksultanov.com/projects/'
    weight = 30
  [[menus.main]]
    name = 'CONTACT'
    url = 'https://nurbeksultanov.com/contact/'
    weight = 40